name: assignment_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.3
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_sound: ^9.28.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
